[defaults]
export-json = "bench.json"
shell = "bash"

[commands.just-fmt]
command = "just --fmt --unstable"

[commands.nixfmt]
command = """fd --glob "*.nix" -x nixfmt"""

[commands.standard-clj-fmt]
command = "standard-clj fix"

[commands.taplo-fmt]
command = """fd --glob "*.toml" -x taplo fmt"""
